ca = /home/eddy/Docs/SAO/BTA/BTA_utils/BTA_dome_modbus/SSL_socket/ca/ca/ca_cert.pem
certificate = /home/eddy/Docs/SAO/BTA/BTA_utils/BTA_dome_modbus/SSL_socket/ca/server/server_cert.pem
key = /home/eddy/Docs/SAO/BTA/BTA_utils/BTA_dome_modbus/SSL_socket/ca/server/private/server_key.pem
logfile = /home/eddy/Docs/SAO/BTA/BTA_utils/BTA_dome_modbus/SSL_socket/server.log
serialdev = /dev/ttyUSB0
serialspeed = 19200
ioid = 20
verbose = 3
